## https://github.com/docker/build-push-action


name: php 8.3 Swoole ZTS

## 手动调度
on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Login to cr.console.aliyun.com
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_ALIYUN_USERNAME }}
          password: ${{ secrets.DOCKER_ALIYUN_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.8.3-zts
          push: true
          tags: |
            lzh1104/php-rc:8.3-zts
            registry.cn-hangzhou.aliyuncs.com/lzh1104/php-rc:8.3-zts
